/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package model.registration;

import classes.FDA;
import classes.Patient;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.sendmail.testEmail;
import util.sql.FDASqlQuery;

/**
 *
 * @author sunayanashivanagi
 */
public class FDAFormJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FDAFormJPanel
     */
    private boolean validation;
    javax.swing.JSplitPane splitPane;
    public FDAFormJPanel(javax.swing.JSplitPane splitPane) {
        initComponents();
        this.splitPane=splitPane;
        comboboxCountry.setSelectedIndex(0);
        formReset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblFDA = new javax.swing.JLabel();
        lblBoardName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        valBoardName = new javax.swing.JLabel();
        lblCountry = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 40), new java.awt.Dimension(0, 40), new java.awt.Dimension(32767, 40));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 32767));
        btnReset = new javax.swing.JButton();
        btnsubmit = new javax.swing.JButton();
        lbllogo = new javax.swing.JLabel();
        comboboxCountry = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        valCity = new javax.swing.JLabel();
        lblEmailId = new javax.swing.JLabel();
        txtEmailId = new javax.swing.JTextField();
        valEmailId = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        valPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblPhoneNumber = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        valPhoneNumber = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFDA.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        lblFDA.setForeground(new java.awt.Color(0, 51, 153));
        lblFDA.setText("Enter FDA Details");
        jPanel2.add(lblFDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 540, 90));

        lblBoardName.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblBoardName.setForeground(new java.awt.Color(102, 102, 102));
        lblBoardName.setText("Board Name");
        jPanel2.add(lblBoardName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 150, 30));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel2.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 290, 30));

        valBoardName.setForeground(new java.awt.Color(255, 61, 0));
        valBoardName.setText("Please enter valid Board Name");
        jPanel2.add(valBoardName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 290, 20));

        lblCountry.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblCountry.setForeground(new java.awt.Color(102, 102, 102));
        lblCountry.setText("Country");
        jPanel2.add(lblCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 170, 30));
        jPanel2.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 710, -1, 90));
        jPanel2.add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, 190, 0));

        btnReset.setBackground(new java.awt.Color(255, 51, 0));
        btnReset.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/Reverse.png"))); // NOI18N
        btnReset.setText("RESET");
        btnReset.setIconTextGap(10);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel2.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 700, 160, 40));

        btnsubmit.setBackground(new java.awt.Color(0, 153, 0));
        btnsubmit.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnsubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnsubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/Double Tick.png"))); // NOI18N
        btnsubmit.setText("SUBMIT");
        btnsubmit.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        jPanel2.add(btnsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 700, 160, 40));

        lbllogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/AVSlogo.png"))); // NOI18N
        jPanel2.add(lbllogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 730, 110, 70));

        comboboxCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "India", "United States", "Canada", "China", "Japan", "South Korea", "Germany" }));
        comboboxCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxCountryActionPerformed(evt);
            }
        });
        jPanel2.add(comboboxCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 290, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/FDA.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 390, 580));

        lblCity.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblCity.setForeground(new java.awt.Color(102, 102, 102));
        lblCity.setText("City");
        jPanel2.add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 120, 30));

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });
        jPanel2.add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 290, 30));

        valCity.setForeground(new java.awt.Color(255, 61, 0));
        valCity.setText("Please enter valid City");
        jPanel2.add(valCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 290, 20));

        lblEmailId.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblEmailId.setForeground(new java.awt.Color(102, 102, 102));
        lblEmailId.setText("Email Id");
        jPanel2.add(lblEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 70, 30));

        txtEmailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailIdActionPerformed(evt);
            }
        });
        jPanel2.add(txtEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 290, 30));

        valEmailId.setForeground(new java.awt.Color(255, 61, 0));
        valEmailId.setText("Please enter valid Email Id");
        jPanel2.add(valEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 290, 20));

        lblPassword.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(102, 102, 102));
        lblPassword.setText("Password");
        jPanel2.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 110, 30));

        valPassword.setForeground(new java.awt.Color(255, 61, 0));
        valPassword.setText("Please enter valid Password");
        jPanel2.add(valPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, 290, 20));
        jPanel2.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 290, 30));

        lblPhoneNumber.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblPhoneNumber.setForeground(new java.awt.Color(102, 102, 102));
        lblPhoneNumber.setText("Phone Number");
        jPanel2.add(lblPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 570, 140, 30));

        txtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumberActionPerformed(evt);
            }
        });
        jPanel2.add(txtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 600, 290, 30));

        valPhoneNumber.setForeground(new java.awt.Color(255, 61, 0));
        valPhoneNumber.setText("Please enter valid Phone Number");
        jPanel2.add(valPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, 290, 20));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        formReset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        // TODO add your handling code here:
         
         String city = txtCity.getText();
         String name = txtName.getText();
         String Country = String.valueOf(comboboxCountry.getSelectedItem());
         String Email_Id = txtEmailId.getText();
        String Phone_No = txtPhoneNumber.getText();
        String Password = txtPassword.getText();
        
         FDASqlQuery sql = new FDASqlQuery();
         int result=0;
         
         FDA obj = new FDA();
         
         obj.setFDA_City(city);
         obj.setFDA_Board_Name(name);
         obj.setFDA_Country(Country);
         obj.setEmail_Id(Email_Id);
         obj.setPassword(Password);
         obj.setPhone_No(Phone_No);
         
         System.out.println("FDA Object->"+obj);
          if (validation()) {
              testEmail a = new testEmail();
            try {
                a.sendMail(Email_Id,"AVS Pharmacy -  Account Creation","FDA account created successfully !");
            } catch (Exception ex) {
                Logger.getLogger(PatientRegFormJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
         result = sql.createFDA(obj);
        }
        if (result == 1) {
            formReset();        
            splitPane.setRightComponent(new SuccessGifJPanel());
        } else {
            validation();
            JOptionPane.showMessageDialog(this, "FDA not created !");

        }
        
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void comboboxCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxCountryActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtEmailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailIdActionPerformed

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberActionPerformed
    private void formReset() {

        txtName.setText("");
        txtCity.setText("");
        comboboxCountry.setSelectedIndex(1);
        txtEmailId.setText("");
        txtPassword.setText("");
        txtPhoneNumber.setText("");
        

        valBoardName.setText("");
        valCity.setText("");
        valEmailId.setText("");
        valPhoneNumber.setText("");
        valPassword.setText("");
    }
    
    private boolean validation() {
        boolean validation = true;
        
        
      
        valBoardName.setText("");
        valCity.setText("");
        valEmailId.setText("");
        valPassword.setText("");
        valPhoneNumber.setText("");
        
         String city = txtCity.getText();
         String name = txtName.getText();
         String Email_Id = txtEmailId.getText();
         String Phone_No = txtPhoneNumber.getText();
         String Password = txtPassword.getText();

        System.out.println("FDA Name->" + name);

        //Name Validation
        if (name.length() <= 0) {
            valBoardName.setText("Please Enter Board Name");
            validation = false;
        }
        
        //City Amount Validation
        if (city.length() <= 0) {
            valCity.setText("Please Enter valid City");
            validation = false;
        }
        
       //Email_Id Validation
        if (Email_Id.length() <= 0) {
            valEmailId.setText("Please Enter EmailId");
            validation = false;
        }
        
        //Password Validation
        if (Password.length() <= 0) {
            valPassword.setText("Please Enter Password");
            validation = false;
        }
        
        //Phone_No Validation
        if (Phone_No.length() <= 0) {
            valPhoneNumber.setText("Please Enter Phone_No");
            validation = false;
        }
        
        return validation;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JComboBox<String> comboboxCountry;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBoardName;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblEmailId;
    private javax.swing.JLabel lblFDA;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtEmailId;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JLabel valBoardName;
    private javax.swing.JLabel valCity;
    private javax.swing.JLabel valEmailId;
    private javax.swing.JLabel valPassword;
    private javax.swing.JLabel valPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
