/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package model.distributor;

import model.main.MainJFrame;

/**
 *
 * @author sunayanashivanagi
 */
public class DistributorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DistributorJPanel
     */
    public DistributorJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelInventoryM = new javax.swing.JTabbedPane();
        panOrderManagement = new javax.swing.JPanel();
        lblOrderTable = new javax.swing.JLabel();
        lbllogo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        btnOrderDelete = new javax.swing.JButton();
        btnOrderUpdate1 = new javax.swing.JButton();
        panInventoryManagement = new javax.swing.JPanel();
        lbllogo1 = new javax.swing.JLabel();
        lblDestination = new javax.swing.JLabel();
        lblDisDelivery = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        txtManufacturerName = new javax.swing.JTextField();
        valManufacturerName = new javax.swing.JLabel();
        lblDOD = new javax.swing.JLabel();
        drpChooseHospital = new javax.swing.JComboBox<>();
        btnResetMed = new javax.swing.JButton();
        btnsubmitMed = new javax.swing.JButton();
        dateDOM = new com.toedter.calendar.JDateChooser();
        comboCategoryMed1 = new javax.swing.JComboBox<>();
        lblDisHospital = new javax.swing.JLabel();
        btnPharmacy = new javax.swing.JRadioButton();
        btnHospital = new javax.swing.JRadioButton();
        lblDisMedicine = new javax.swing.JLabel();
        comboCategoryMed2 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Distributor");

        PanelInventoryM.setBackground(new java.awt.Color(255, 255, 255));
        PanelInventoryM.setForeground(new java.awt.Color(0, 51, 153));
        PanelInventoryM.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N

        panOrderManagement.setBackground(new java.awt.Color(255, 255, 255));
        panOrderManagement.setForeground(new java.awt.Color(0, 51, 153));
        panOrderManagement.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOrderTable.setBackground(new java.awt.Color(255, 255, 255));
        lblOrderTable.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        lblOrderTable.setForeground(new java.awt.Color(153, 153, 153));
        lblOrderTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/Shipped.png"))); // NOI18N
        lblOrderTable.setText("Manage Shipment");
        lblOrderTable.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lblOrderTable.setIconTextGap(10);
        panOrderManagement.add(lblOrderTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 24, 499, 56));

        lbllogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/AVSlogo.png"))); // NOI18N
        panOrderManagement.add(lbllogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 608, 110, 70));

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Ingredient Id", "Transaction Id", "Manufacturer Id", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblOrder);

        panOrderManagement.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 114, 764, 440));

        btnOrderDelete.setBackground(new java.awt.Color(255, 0, 51));
        btnOrderDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnOrderDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/Remove.png"))); // NOI18N
        btnOrderDelete.setText("DELETE");
        panOrderManagement.add(btnOrderDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 590, 120, 40));

        btnOrderUpdate1.setBackground(new java.awt.Color(255, 204, 0));
        btnOrderUpdate1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnOrderUpdate1.setForeground(new java.awt.Color(255, 255, 255));
        btnOrderUpdate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/Available Updates.png"))); // NOI18N
        btnOrderUpdate1.setText("UPDATE");
        btnOrderUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderUpdate1ActionPerformed(evt);
            }
        });
        panOrderManagement.add(btnOrderUpdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 590, 130, 40));

        PanelInventoryM.addTab("Manage Shipment", panOrderManagement);

        panInventoryManagement.setBackground(new java.awt.Color(255, 255, 255));
        panInventoryManagement.setForeground(new java.awt.Color(255, 255, 255));
        panInventoryManagement.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbllogo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/AVSlogo.png"))); // NOI18N
        panInventoryManagement.add(lbllogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 608, 110, 70));

        lblDestination.setFont(new java.awt.Font("Helvetica Neue", 1, 19)); // NOI18N
        lblDestination.setForeground(new java.awt.Color(102, 102, 102));
        lblDestination.setText("Choose a Destination");
        panInventoryManagement.add(lblDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 290, 30));

        lblDisDelivery.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblDisDelivery.setForeground(new java.awt.Color(102, 102, 102));
        lblDisDelivery.setText("Mode of Delivery");
        panInventoryManagement.add(lblDisDelivery, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 290, 30));

        lblPrice.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(102, 102, 102));
        lblPrice.setText("Price");
        panInventoryManagement.add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 290, 30));

        txtManufacturerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManufacturerNameActionPerformed(evt);
            }
        });
        panInventoryManagement.add(txtManufacturerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 290, 30));

        valManufacturerName.setForeground(new java.awt.Color(255, 61, 0));
        valManufacturerName.setText("Please enter valid price");
        panInventoryManagement.add(valManufacturerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 290, 20));

        lblDOD.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblDOD.setForeground(new java.awt.Color(102, 102, 102));
        lblDOD.setText("Date of Delivery");
        panInventoryManagement.add(lblDOD, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 290, 30));

        drpChooseHospital.setForeground(new java.awt.Color(0, 0, 153));
        drpChooseHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drpChooseHospitalActionPerformed(evt);
            }
        });
        panInventoryManagement.add(drpChooseHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 290, 30));

        btnResetMed.setBackground(new java.awt.Color(255, 51, 0));
        btnResetMed.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnResetMed.setForeground(new java.awt.Color(255, 255, 255));
        btnResetMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/Reverse.png"))); // NOI18N
        btnResetMed.setText("RESET");
        btnResetMed.setIconTextGap(10);
        btnResetMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetMedActionPerformed(evt);
            }
        });
        panInventoryManagement.add(btnResetMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, 140, 40));

        btnsubmitMed.setBackground(new java.awt.Color(0, 153, 0));
        btnsubmitMed.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnsubmitMed.setForeground(new java.awt.Color(255, 255, 255));
        btnsubmitMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/Double Tick.png"))); // NOI18N
        btnsubmitMed.setText("SUBMIT");
        btnsubmitMed.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnsubmitMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitMedActionPerformed(evt);
            }
        });
        panInventoryManagement.add(btnsubmitMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, 140, 40));
        panInventoryManagement.add(dateDOM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 290, 30));

        comboCategoryMed1.setForeground(new java.awt.Color(0, 51, 153));
        comboCategoryMed1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Air", "Road", "Sea", "Rail" }));
        panInventoryManagement.add(comboCategoryMed1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 290, 30));

        lblDisHospital.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblDisHospital.setForeground(new java.awt.Color(102, 102, 102));
        lblDisHospital.setText("Choose Hospital");
        panInventoryManagement.add(lblDisHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 290, 30));

        btnPharmacy.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnPharmacy.setForeground(new java.awt.Color(102, 102, 102));
        btnPharmacy.setText("Pharmacy");
        btnPharmacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPharmacyActionPerformed(evt);
            }
        });
        panInventoryManagement.add(btnPharmacy, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 120, -1));

        btnHospital.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnHospital.setForeground(new java.awt.Color(102, 102, 102));
        btnHospital.setText("Hospital");
        panInventoryManagement.add(btnHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 120, -1));

        lblDisMedicine.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblDisMedicine.setForeground(new java.awt.Color(102, 102, 102));
        lblDisMedicine.setText("Choose Medicine");
        panInventoryManagement.add(lblDisMedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 290, 30));

        comboCategoryMed2.setForeground(new java.awt.Color(0, 0, 153));
        panInventoryManagement.add(comboCategoryMed2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 290, 30));

        PanelInventoryM.addTab("Create Shipment", panInventoryManagement);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PanelInventoryM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(PanelInventoryM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtManufacturerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManufacturerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManufacturerNameActionPerformed

    private void drpChooseHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drpChooseHospitalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drpChooseHospitalActionPerformed

    private void btnResetMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetMedActionPerformed

    private void btnsubmitMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsubmitMedActionPerformed

    private void btnOrderUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderUpdate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOrderUpdate1ActionPerformed

    private void btnPharmacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPharmacyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPharmacyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane PanelInventoryM;
    private javax.swing.JRadioButton btnHospital;
    private javax.swing.JButton btnOrderDelete;
    private javax.swing.JButton btnOrderUpdate1;
    private javax.swing.JRadioButton btnPharmacy;
    private javax.swing.JButton btnResetMed;
    private javax.swing.JButton btnsubmitMed;
    private javax.swing.JComboBox<String> comboCategoryMed1;
    private javax.swing.JComboBox<String> comboCategoryMed2;
    private com.toedter.calendar.JDateChooser dateDOM;
    private javax.swing.JComboBox<String> drpChooseHospital;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDOD;
    private javax.swing.JLabel lblDestination;
    private javax.swing.JLabel lblDisDelivery;
    private javax.swing.JLabel lblDisHospital;
    private javax.swing.JLabel lblDisMedicine;
    private javax.swing.JLabel lblOrderTable;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JLabel lbllogo1;
    private javax.swing.JPanel panInventoryManagement;
    private javax.swing.JPanel panOrderManagement;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTextField txtManufacturerName;
    private javax.swing.JLabel valManufacturerName;
    // End of variables declaration//GEN-END:variables
}
