/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package model.manufacturer;

import classes.Manufacturer;
import classes.Medicine;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.sql.MedicineSqlQuery;

/**
 *
 * @author sunayanashivanagi
 */
public class PackagingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PackagingJPanel
     */
    javax.swing.JSplitPane splitPane;
    Manufacturer manufacturer;
    ArrayList<Medicine> mList = new ArrayList<>();
    public PackagingJPanel(javax.swing.JSplitPane splitPane,Manufacturer manufacturer) {
        initComponents();
        this.manufacturer=manufacturer;
        populateTable();
        
        MedicineSqlQuery msq = new MedicineSqlQuery();
        this.mList = msq.readAllMedicine();
        this.splitPane=splitPane;
        for(Medicine m:mList){
            drpMedicineName.addItem(m.getMedicine_Name());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PanelInventoryM = new javax.swing.JTabbedPane();
        panOrderManagement = new javax.swing.JPanel();
        lblOrderTable = new javax.swing.JLabel();
        lbllogo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMedicine = new javax.swing.JTable();
        btnNewOrder = new javax.swing.JButton();
        panInventoryManagement = new javax.swing.JPanel();
        lbllogo1 = new javax.swing.JLabel();
        lblMedicineName = new javax.swing.JLabel();
        lblMedStatus = new javax.swing.JLabel();
        lblMedCategory = new javax.swing.JLabel();
        lblManufacturerN = new javax.swing.JLabel();
        lblShellLife = new javax.swing.JLabel();
        drpMedicineName = new javax.swing.JComboBox<>();
        spinPrice = new javax.swing.JSpinner();
        btnsubmitMed = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        lblMedicineName1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        drpLocation = new javax.swing.JComboBox<>();
        txtQuantity1 = new javax.swing.JSpinner();
        comboCategoryMed2 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Packaging");

        PanelInventoryM.setBackground(new java.awt.Color(255, 255, 255));
        PanelInventoryM.setForeground(new java.awt.Color(0, 51, 153));
        PanelInventoryM.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N

        panOrderManagement.setBackground(new java.awt.Color(255, 255, 255));
        panOrderManagement.setForeground(new java.awt.Color(0, 51, 153));
        panOrderManagement.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOrderTable.setBackground(new java.awt.Color(255, 255, 255));
        lblOrderTable.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        lblOrderTable.setForeground(new java.awt.Color(153, 153, 153));
        lblOrderTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/Full Shopping Basket.png"))); // NOI18N
        lblOrderTable.setText("Manage Package");
        lblOrderTable.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lblOrderTable.setIconTextGap(10);
        panOrderManagement.add(lblOrderTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 24, 499, 56));

        lbllogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/AVSlogo.png"))); // NOI18N
        panOrderManagement.add(lbllogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 608, 110, 70));

        tblMedicine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Medicine Name", "Medicine Category", "Date of Manufacturing", "Manufacturer Name", "Medicine Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblMedicine);

        panOrderManagement.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 114, 764, 440));

        btnNewOrder.setBackground(new java.awt.Color(0, 153, 255));
        btnNewOrder.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnNewOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnNewOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/Eye.png"))); // NOI18N
        btnNewOrder.setText("VIEW");
        btnNewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewOrderActionPerformed(evt);
            }
        });
        panOrderManagement.add(btnNewOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 580, 120, 34));

        PanelInventoryM.addTab("Manage Package", panOrderManagement);

        panInventoryManagement.setBackground(new java.awt.Color(255, 255, 255));
        panInventoryManagement.setForeground(new java.awt.Color(255, 255, 255));
        panInventoryManagement.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbllogo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/AVSlogo.png"))); // NOI18N
        panInventoryManagement.add(lbllogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 608, 110, 70));

        lblMedicineName.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblMedicineName.setForeground(new java.awt.Color(102, 102, 102));
        lblMedicineName.setText("Price");
        panInventoryManagement.add(lblMedicineName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 290, 30));

        lblMedStatus.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblMedStatus.setForeground(new java.awt.Color(102, 102, 102));
        lblMedStatus.setText(" Status");
        panInventoryManagement.add(lblMedStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 290, 30));

        lblMedCategory.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblMedCategory.setForeground(new java.awt.Color(102, 102, 102));
        lblMedCategory.setText("Package Type");
        panInventoryManagement.add(lblMedCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 290, 30));

        lblManufacturerN.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblManufacturerN.setForeground(new java.awt.Color(102, 102, 102));
        lblManufacturerN.setText("Location");
        panInventoryManagement.add(lblManufacturerN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 290, 30));

        lblShellLife.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblShellLife.setForeground(new java.awt.Color(102, 102, 102));
        lblShellLife.setText("Quantity");
        panInventoryManagement.add(lblShellLife, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 290, 30));

        drpMedicineName.setForeground(new java.awt.Color(0, 0, 153));
        drpMedicineName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drpMedicineNameActionPerformed(evt);
            }
        });
        panInventoryManagement.add(drpMedicineName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 290, 30));

        spinPrice.setModel(new javax.swing.SpinnerNumberModel(50, 1, 1000, 20));
        panInventoryManagement.add(spinPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 80, 30));

        btnsubmitMed.setBackground(new java.awt.Color(0, 153, 0));
        btnsubmitMed.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnsubmitMed.setForeground(new java.awt.Color(255, 255, 255));
        btnsubmitMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/Double Tick.png"))); // NOI18N
        btnsubmitMed.setText("SUBMIT");
        btnsubmitMed.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnsubmitMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitMedActionPerformed(evt);
            }
        });
        panInventoryManagement.add(btnsubmitMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 350, 40));

        jTextField1.setText("Available");
        jTextField1.setEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        panInventoryManagement.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 280, 30));

        lblMedicineName1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblMedicineName1.setForeground(new java.awt.Color(102, 102, 102));
        lblMedicineName1.setText("Medicine Name");
        panInventoryManagement.add(lblMedicineName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 290, 30));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("USD");
        panInventoryManagement.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, 30));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("KG");
        panInventoryManagement.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 30, 30));

        drpLocation.setForeground(new java.awt.Color(0, 0, 153));
        drpLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boston", "New york", "California", "Seattle", "Dallas", "New Jersey" }));
        drpLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drpLocationActionPerformed(evt);
            }
        });
        panInventoryManagement.add(drpLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 290, 30));

        txtQuantity1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        panInventoryManagement.add(txtQuantity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 80, 30));

        comboCategoryMed2.setForeground(new java.awt.Color(0, 0, 153));
        comboCategoryMed2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paperboard boxes", "Corrugated boxes", "Plastic boxes", "Rigid boxes", "Chipboard packaging", "Poly bags", "Foil sealed bags" }));
        comboCategoryMed2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCategoryMed2ActionPerformed(evt);
            }
        });
        panInventoryManagement.add(comboCategoryMed2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 290, 30));

        PanelInventoryM.addTab("Create Package", panInventoryManagement);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PanelInventoryM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(PanelInventoryM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnsubmitMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitMedActionPerformed
        // TODO add your handling code here:
         MedicineSqlQuery msq = new MedicineSqlQuery();
         Medicine m = mList.get(drpMedicineName.getSelectedIndex());
        m.setMedicine_Status("Available");
        msq.updateMedicine(m);
        populateTable();
        splitPane.setRightComponent(new SubmitGifJPanel());
    }//GEN-LAST:event_btnsubmitMedActionPerformed

    private void drpMedicineNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drpMedicineNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drpMedicineNameActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnNewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewOrderActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblMedicine.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to edit");
            return;
        }

        ArrayList<Medicine> mList = new ArrayList<>();
        MedicineSqlQuery msq = new MedicineSqlQuery();
        mList = msq.readAllMedicine();
        Medicine m = mList.get(selectedRow);
        new PackagingJDialog(null, true, m).show();
        populateTable();
    }//GEN-LAST:event_btnNewOrderActionPerformed

    private void drpLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drpLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drpLocationActionPerformed

    private void comboCategoryMed2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCategoryMed2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCategoryMed2ActionPerformed
    private void populateTable() {
        ArrayList<Medicine> mList = new ArrayList<>();
        MedicineSqlQuery msq = new MedicineSqlQuery();
        mList = msq.readAllMedicinebyMName(manufacturer.getManufacturer_Name());

        DefaultTableModel model = (DefaultTableModel) tblMedicine.getModel();
        model.setRowCount(0);

        for (Medicine e : mList) {
            Object row[] = new Object[10];
            row[0] = e.getMedicine_Name();
            row[1] = e.getMedicine_Category();
            row[2] = e.getDate_Of_Manufacture();
            row[3] = e.getManufacturer_Name();
            row[4] = e.getMedicine_Status();

            if ((e.getMedicine_Status().equals("Ready for Shipment"))
                    || (e.getMedicine_Status().equals("Rejected"))||
                    (e.getMedicine_Status().equals("Available")) ){
                model.addRow(row);
            }

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane PanelInventoryM;
    private javax.swing.JButton btnNewOrder;
    private javax.swing.JButton btnsubmitMed;
    private javax.swing.JComboBox<String> comboCategoryMed2;
    private javax.swing.JComboBox<String> drpLocation;
    private javax.swing.JComboBox<String> drpMedicineName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblManufacturerN;
    private javax.swing.JLabel lblMedCategory;
    private javax.swing.JLabel lblMedStatus;
    private javax.swing.JLabel lblMedicineName;
    private javax.swing.JLabel lblMedicineName1;
    private javax.swing.JLabel lblOrderTable;
    private javax.swing.JLabel lblShellLife;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JLabel lbllogo1;
    private javax.swing.JPanel panInventoryManagement;
    private javax.swing.JPanel panOrderManagement;
    private javax.swing.JSpinner spinPrice;
    private javax.swing.JTable tblMedicine;
    private javax.swing.JSpinner txtQuantity1;
    // End of variables declaration//GEN-END:variables
}
