/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package model.manufacturer;

/**
 *
 * @author sunayanashivanagi
 */
public class PackagingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PackagingJPanel
     */
    public PackagingJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PanelInventoryM = new javax.swing.JTabbedPane();
        panOrderManagement = new javax.swing.JPanel();
        lblOrderTable = new javax.swing.JLabel();
        lbllogo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        btnOrderView = new javax.swing.JButton();
        btnOrderDelete = new javax.swing.JButton();
        panInventoryManagement = new javax.swing.JPanel();
        lbllogo1 = new javax.swing.JLabel();
        lblMedicineName = new javax.swing.JLabel();
        txtMedicineName = new javax.swing.JTextField();
        valMedName = new javax.swing.JLabel();
        lblMedStatus = new javax.swing.JLabel();
        lblMedCategory = new javax.swing.JLabel();
        lblManufacturerN = new javax.swing.JLabel();
        txtManufacturerName = new javax.swing.JTextField();
        valManufacturerName = new javax.swing.JLabel();
        lblDOM = new javax.swing.JLabel();
        lblShellLife = new javax.swing.JLabel();
        drpStatusofMedicine = new javax.swing.JComboBox<>();
        comboCategoryMed = new javax.swing.JComboBox<>();
        spinShellLife = new javax.swing.JSpinner();
        btnResetMed = new javax.swing.JButton();
        btnsubmitMed = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        lblMedicineName1 = new javax.swing.JLabel();
        txtMedicineName1 = new javax.swing.JTextField();
        valMedName1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Packaging");

        PanelInventoryM.setBackground(new java.awt.Color(255, 255, 255));
        PanelInventoryM.setForeground(new java.awt.Color(0, 51, 153));
        PanelInventoryM.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N

        panOrderManagement.setBackground(new java.awt.Color(255, 255, 255));
        panOrderManagement.setForeground(new java.awt.Color(0, 51, 153));
        panOrderManagement.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOrderTable.setBackground(new java.awt.Color(255, 255, 255));
        lblOrderTable.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        lblOrderTable.setForeground(new java.awt.Color(153, 153, 153));
        lblOrderTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/Full Shopping Basket.png"))); // NOI18N
        lblOrderTable.setText("Manage Package");
        lblOrderTable.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lblOrderTable.setIconTextGap(10);
        panOrderManagement.add(lblOrderTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 24, 499, 56));

        lbllogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/AVSlogo.png"))); // NOI18N
        panOrderManagement.add(lbllogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 608, 110, 70));

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Ingredient Id", "Transaction Id", "Manufacturer Id", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblOrder);

        panOrderManagement.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 114, 764, 440));

        btnOrderView.setBackground(new java.awt.Color(0, 153, 255));
        btnOrderView.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnOrderView.setForeground(new java.awt.Color(255, 255, 255));
        btnOrderView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/Eye.png"))); // NOI18N
        btnOrderView.setText("VIEW");
        btnOrderView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderViewActionPerformed(evt);
            }
        });
        panOrderManagement.add(btnOrderView, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 590, 130, 40));

        btnOrderDelete.setBackground(new java.awt.Color(255, 0, 51));
        btnOrderDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnOrderDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/Remove.png"))); // NOI18N
        btnOrderDelete.setText("DELETE");
        panOrderManagement.add(btnOrderDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 590, 120, 40));

        PanelInventoryM.addTab("Manage Package", panOrderManagement);

        panInventoryManagement.setBackground(new java.awt.Color(255, 255, 255));
        panInventoryManagement.setForeground(new java.awt.Color(255, 255, 255));
        panInventoryManagement.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbllogo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/AVSlogo.png"))); // NOI18N
        panInventoryManagement.add(lbllogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 608, 110, 70));

        lblMedicineName.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblMedicineName.setForeground(new java.awt.Color(102, 102, 102));
        lblMedicineName.setText("Price");
        panInventoryManagement.add(lblMedicineName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 290, 30));

        txtMedicineName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicineNameActionPerformed(evt);
            }
        });
        panInventoryManagement.add(txtMedicineName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 250, 30));

        valMedName.setForeground(new java.awt.Color(255, 61, 0));
        valMedName.setText("Please enter valid price");
        panInventoryManagement.add(valMedName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 290, 20));

        lblMedStatus.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblMedStatus.setForeground(new java.awt.Color(102, 102, 102));
        lblMedStatus.setText(" Status");
        panInventoryManagement.add(lblMedStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 290, 30));

        lblMedCategory.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblMedCategory.setForeground(new java.awt.Color(102, 102, 102));
        lblMedCategory.setText("Package Type");
        panInventoryManagement.add(lblMedCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 290, 30));

        lblManufacturerN.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblManufacturerN.setForeground(new java.awt.Color(102, 102, 102));
        lblManufacturerN.setText("Location");
        panInventoryManagement.add(lblManufacturerN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 290, 30));

        txtManufacturerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManufacturerNameActionPerformed(evt);
            }
        });
        panInventoryManagement.add(txtManufacturerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 290, 30));

        valManufacturerName.setForeground(new java.awt.Color(255, 61, 0));
        valManufacturerName.setText("Please enter valid location");
        panInventoryManagement.add(valManufacturerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 290, 20));

        lblDOM.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblDOM.setForeground(new java.awt.Color(102, 102, 102));
        lblDOM.setText("Distributor");
        panInventoryManagement.add(lblDOM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 290, 30));

        lblShellLife.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblShellLife.setForeground(new java.awt.Color(102, 102, 102));
        lblShellLife.setText("Quantity");
        panInventoryManagement.add(lblShellLife, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 290, 30));

        drpStatusofMedicine.setForeground(new java.awt.Color(0, 0, 153));
        drpStatusofMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drpStatusofMedicineActionPerformed(evt);
            }
        });
        panInventoryManagement.add(drpStatusofMedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 290, 30));

        comboCategoryMed.setForeground(new java.awt.Color(0, 0, 153));
        comboCategoryMed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paperboard boxes", "Corrugated boxes", "Plastic boxes", "Rigid boxes", "Chipboard packaging", "Poly bags", "Foil sealed bags" }));
        comboCategoryMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCategoryMedActionPerformed(evt);
            }
        });
        panInventoryManagement.add(comboCategoryMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 290, 30));
        panInventoryManagement.add(spinShellLife, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 80, 30));

        btnResetMed.setBackground(new java.awt.Color(255, 51, 0));
        btnResetMed.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnResetMed.setForeground(new java.awt.Color(255, 255, 255));
        btnResetMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/Reverse.png"))); // NOI18N
        btnResetMed.setText("RESET");
        btnResetMed.setIconTextGap(10);
        btnResetMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetMedActionPerformed(evt);
            }
        });
        panInventoryManagement.add(btnResetMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, 140, 40));

        btnsubmitMed.setBackground(new java.awt.Color(0, 153, 0));
        btnsubmitMed.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnsubmitMed.setForeground(new java.awt.Color(255, 255, 255));
        btnsubmitMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/Double Tick.png"))); // NOI18N
        btnsubmitMed.setText("SUBMIT");
        btnsubmitMed.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnsubmitMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitMedActionPerformed(evt);
            }
        });
        panInventoryManagement.add(btnsubmitMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, 140, 40));

        jTextField1.setText("Ready for Distribution");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        panInventoryManagement.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 280, 30));

        lblMedicineName1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblMedicineName1.setForeground(new java.awt.Color(102, 102, 102));
        lblMedicineName1.setText("Medicine Name");
        panInventoryManagement.add(lblMedicineName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 290, 30));

        txtMedicineName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicineName1ActionPerformed(evt);
            }
        });
        panInventoryManagement.add(txtMedicineName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 290, 30));

        valMedName1.setForeground(new java.awt.Color(255, 61, 0));
        valMedName1.setText("Please enter valid medicine name");
        panInventoryManagement.add(valMedName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 290, 20));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("USD");
        panInventoryManagement.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, 30));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("KG");
        panInventoryManagement.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 30, 30));

        PanelInventoryM.addTab("Create Package", panInventoryManagement);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PanelInventoryM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(PanelInventoryM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrderViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderViewActionPerformed
        // TODO add your handling code here:
         new MedicineDetailsManufacturerJDialog(null,true).show();
    }//GEN-LAST:event_btnOrderViewActionPerformed

    private void txtMedicineNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicineNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicineNameActionPerformed

    private void txtManufacturerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManufacturerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManufacturerNameActionPerformed

    private void drpStatusofMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drpStatusofMedicineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drpStatusofMedicineActionPerformed

    private void btnResetMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetMedActionPerformed

    private void btnsubmitMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsubmitMedActionPerformed

    private void txtMedicineName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicineName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicineName1ActionPerformed

    private void comboCategoryMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCategoryMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCategoryMedActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane PanelInventoryM;
    private javax.swing.JButton btnOrderDelete;
    private javax.swing.JButton btnOrderView;
    private javax.swing.JButton btnResetMed;
    private javax.swing.JButton btnsubmitMed;
    private javax.swing.JComboBox<String> comboCategoryMed;
    private javax.swing.JComboBox<String> drpStatusofMedicine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblDOM;
    private javax.swing.JLabel lblManufacturerN;
    private javax.swing.JLabel lblMedCategory;
    private javax.swing.JLabel lblMedStatus;
    private javax.swing.JLabel lblMedicineName;
    private javax.swing.JLabel lblMedicineName1;
    private javax.swing.JLabel lblOrderTable;
    private javax.swing.JLabel lblShellLife;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JLabel lbllogo1;
    private javax.swing.JPanel panInventoryManagement;
    private javax.swing.JPanel panOrderManagement;
    private javax.swing.JSpinner spinShellLife;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTextField txtManufacturerName;
    private javax.swing.JTextField txtMedicineName;
    private javax.swing.JTextField txtMedicineName1;
    private javax.swing.JLabel valManufacturerName;
    private javax.swing.JLabel valMedName;
    private javax.swing.JLabel valMedName1;
    // End of variables declaration//GEN-END:variables
}
